create table aggregate (id int,val float);
insert into aggregate values(1,5.5);
insert into aggregate values(3,4.5);
insert into aggregate values(5,10.0);
select MAX(id) as max_id from aggregate;
select MIN(val) as min_val from aggregate;
create table aggregate_name (name char(8),id int);
insert into aggregate_name values('qwerasdf',1);
insert into aggregate_name values('uiophjkl',2);
insert into aggregate_name values('asdfhjkl',3);
select MAX(name) as max_name from aggregate_name;
select MIN(name) as min_name from aggregate_name;
